/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorPais;
import Controlador.ControladorPersonas;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Carolina
 */
public class FramePersonas extends javax.swing.JFrame {
    ControladorPersonas cP;
    ControladorPais controladorPais;
    
    /**
     * Creates new form FramePersonas
     */
    public FramePersonas(ControladorPersonas cP, ControladorPais controladorPais) {
        initComponents();
        this.controladorPais = controladorPais;
        this.cP = cP;
        btnGuardar.addActionListener(cP);
        ButtonGroup group = new ButtonGroup();
        group.add(radio_cuidadano);
        group.add(radio_indigena);
        group.add(radio_migrante);
        group.add(radio_refugiado);
        radio_cuidadano.setSelected(true);
        
    }
    
    public void agregarAlCombo(){
        comboPaisActual.removeAllItems();
        comboPaisOrigen.removeAllItems();
        for(String valor : controladorPais.getArreglo()){
            comboPaisActual.addItem(valor);
            comboPaisOrigen.addItem(valor);
        }
    }
     public String getIdentidad(){
         return txtIdentidad.getText();
     }
    
    public String getProcedencia(){
         return txtProcedencia.getText();
     }
    
    public String getEstatus(){       
         String estatus="";
         if(radio_cuidadano.isSelected()){
             return estatus = "Cuidadano";
         } else if(radio_indigena.isSelected()){
             return estatus = "Indigena";
         } else if(radio_migrante.isSelected()){
             return estatus = "Migrante";
         } else if(radio_refugiado.isSelected()){
             return estatus = "Refugiado";
         }
         return estatus;    
    }
    
    public String getPaisOrigen(){   
       return comboPaisOrigen.getItemAt(comboPaisOrigen.getSelectedIndex());       
    }
    
    public String getPaisActual(){   
       return comboPaisActual.getItemAt(comboPaisActual.getSelectedIndex());       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_cuidadano = new javax.swing.JRadioButton();
        radio_indigena = new javax.swing.JRadioButton();
        radio_migrante = new javax.swing.JRadioButton();
        radio_refugiado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProcedencia = new javax.swing.JTextField();
        comboPaisOrigen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboPaisActual = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radio_cuidadano.setText("Cuidadano");

        radio_indigena.setText("Indigena");

        radio_migrante.setText("Migrante");

        radio_refugiado.setText("Refugiado");

        jLabel1.setText("Identidad:");

        txtIdentidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentidadActionPerformed(evt);
            }
        });

        jLabel2.setText("Procedencia:");

        comboPaisOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPaisOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaisOrigenActionPerformed(evt);
            }
        });

        jLabel3.setText("País de origen:");

        comboPaisActual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("País actual:");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio_cuidadano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radio_indigena)
                        .addGap(27, 27, 27)
                        .addComponent(radio_migrante)
                        .addGap(18, 18, 18)
                        .addComponent(radio_refugiado))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboPaisActual, javax.swing.GroupLayout.Alignment.LEADING, 0, 149, Short.MAX_VALUE)
                        .addComponent(txtProcedencia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtIdentidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboPaisOrigen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_cuidadano)
                    .addComponent(radio_indigena)
                    .addComponent(radio_migrante)
                    .addComponent(radio_refugiado))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaisOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaisActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnGuardar)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdentidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentidadActionPerformed

    private void comboPaisOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaisOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaisOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboPaisActual;
    private javax.swing.JComboBox<String> comboPaisOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton radio_cuidadano;
    private javax.swing.JRadioButton radio_indigena;
    private javax.swing.JRadioButton radio_migrante;
    private javax.swing.JRadioButton radio_refugiado;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtProcedencia;
    // End of variables declaration//GEN-END:variables
}
